import type { ManagementPrincipal, MenuIdentity } from "@code-proxy/api-client";

/**
 * Sidebar and principal fixtures for the legacy management-key mode.
 *
 * A management key authenticates as a service credential, which has no rows in
 * the identity tables and therefore no server-provided menus or permissions.
 * These literals stand in for that response so the panel renders the same
 * navigation it would for a platform admin. They mirror CliRelay's MenuCatalog;
 * when a menu is added or renamed there, it has to be mirrored here or the
 * management-key sidebar silently drifts from the session-based one.
 *
 * Extracted from AuthProvider purely as data — no behaviour lives here.
 */

/** Mirrors CliRelay MenuCatalog so management-key / preview mode has a usable sidebar. */
const menu = (
  partial: Pick<
    MenuIdentity,
    "code" | "type" | "path" | "component" | "label_key" | "icon" | "sort_order"
  > &
    Partial<Pick<MenuIdentity, "parent_code" | "permission_code">>,
): MenuIdentity => ({
  code: partial.code,
  parent_code: partial.parent_code ?? "",
  type: partial.type,
  path: partial.path,
  component: partial.component,
  link_url: "",
  label_key: partial.label_key,
  title: "",
  icon: partial.icon,
  permission_code: partial.permission_code ?? "",
  sort_order: partial.sort_order,
  visible: true,
  enabled: true,
  badge_type: "",
  badge_content: "",
  hide_menu: false,
  system_protected: true,
  version: 1,
});

export const LEGACY_SERVICE_MENUS: MenuIdentity[] = [
  menu({
    code: "dashboard",
    type: "menu",
    path: "/dashboard",
    component: "dashboard",
    label_key: "shell.nav_dashboard",
    icon: "layout-dashboard",
    permission_code: "dashboard.read",
    sort_order: 10,
  }),
  menu({
    code: "group.runtime",
    type: "directory",
    path: "/runtime",
    component: "Layout",
    label_key: "shell.nav_group_runtime",
    icon: "activity",
    sort_order: 20,
  }),
  menu({
    code: "runtime.monitor",
    parent_code: "group.runtime",
    type: "menu",
    path: "/runtime/monitor",
    component: "monitor",
    label_key: "shell.nav_monitor",
    icon: "activity",
    permission_code: "monitor.read",
    sort_order: 10,
  }),
  menu({
    code: "runtime.request-logs",
    parent_code: "group.runtime",
    type: "menu",
    path: "/runtime/request-logs",
    component: "request-logs",
    label_key: "shell.nav_request_logs",
    icon: "scroll-text",
    permission_code: "request_logs.read",
    sort_order: 20,
  }),
  menu({
    code: "runtime.logs",
    parent_code: "group.runtime",
    type: "menu",
    path: "/runtime/logs",
    component: "logs",
    label_key: "shell.nav_logs",
    icon: "file-text",
    permission_code: "system.logs.read",
    sort_order: 30,
  }),
  // Top-level leaf pinned after all groups (matches CliRelay MenuCatalog).
  menu({
    code: "runtime.system",
    type: "menu",
    path: "/runtime/system",
    component: "system",
    label_key: "shell.nav_system",
    icon: "info",
    permission_code: "system.status.read",
    sort_order: 70,
  }),
  menu({
    code: "group.access",
    type: "directory",
    path: "/access",
    component: "Layout",
    label_key: "shell.nav_group_access",
    icon: "bot",
    sort_order: 30,
  }),
  menu({
    code: "access.providers",
    parent_code: "group.access",
    type: "menu",
    path: "/access/ai-providers",
    component: "providers",
    label_key: "shell.nav_ai_providers",
    icon: "bot",
    permission_code: "providers.read",
    sort_order: 10,
  }),
  menu({
    code: "system.account-security",
    parent_code: "group.access",
    type: "menu",
    path: "/access/ai-accounts",
    component: "account-security",
    label_key: "shell.nav_ai_accounts",
    icon: "key-round",
    permission_code: "auth_files.read",
    sort_order: 20,
  }),
  // Hidden from sidebar: key management is under 用户账号 (?endUserId=). Route kept for deep links.
  {
    ...menu({
      code: "access.api-keys",
      parent_code: "group.access",
      type: "menu",
      path: "/access/api-keys",
      component: "api-keys",
      label_key: "shell.nav_api_keys",
      icon: "sparkles",
      permission_code: "api_keys.read",
      sort_order: 30,
    }),
    hide_menu: true,
  },
  menu({
    code: "access.end-users",
    parent_code: "group.access",
    type: "menu",
    path: "/access/end-users",
    component: "end-users",
    // Prefer end_users.read; legacy key admins also get the menu via api_keys.read in can() OR at route gate.
    label_key: "shell.nav_end_users",
    icon: "user-round",
    permission_code: "end_users.read",
    sort_order: 25,
  }),
  menu({
    code: "system.api-key-permissions",
    parent_code: "group.access",
    type: "menu",
    path: "/access/api-key-permissions",
    component: "api-key-permissions",
    label_key: "shell.nav_api_key_permissions",
    icon: "shield-check",
    permission_code: "api_key_profiles.read",
    sort_order: 40,
  }),
  // Stable code matches CliRelay while the page now belongs to Access & Credentials.
  menu({
    code: "runtime.content-moderation",
    parent_code: "group.access",
    type: "menu",
    path: "/access/content-moderation",
    component: "content-moderation",
    label_key: "shell.nav_content_moderation",
    icon: "shield-alert",
    permission_code: "content_moderation.read",
    sort_order: 45,
  }),
  menu({
    code: "access.ccswitch",
    parent_code: "group.access",
    type: "menu",
    path: "/access/ccswitch-import-settings",
    component: "ccswitch-import-settings",
    label_key: "shell.nav_ccswitch_import_settings",
    icon: "arrow-down-to-line",
    // Tenant-scoped: matches /ccswitch-import-configs API auth (routing.read/write).
    // Must not use platform system.config.read, or ordinary tenants never see this menu.
    permission_code: "routing.read",
    sort_order: 50,
  }),
  menu({
    code: "group.models",
    type: "directory",
    path: "/models",
    component: "Layout",
    label_key: "shell.nav_group_models",
    icon: "layers",
    sort_order: 40,
  }),
  menu({
    code: "models.plaza",
    parent_code: "group.models",
    type: "menu",
    path: "/models/plaza",
    component: "model-plaza",
    label_key: "shell.nav_model_plaza",
    icon: "store",
    // Same surface as former System Info "available models": tenant-visible model set.
    permission_code: "system.status.read",
    sort_order: 5,
  }),
  menu({
    code: "models.catalog",
    parent_code: "group.models",
    type: "menu",
    path: "/models/catalog",
    component: "models",
    label_key: "shell.nav_models",
    icon: "cpu",
    permission_code: "models.read",
    sort_order: 10,
  }),
  menu({
    code: "models.image-generation",
    parent_code: "group.models",
    type: "menu",
    path: "/models/image-generation",
    component: "image-generation",
    label_key: "shell.nav_image_generation",
    icon: "image",
    permission_code: "system.config.read",
    sort_order: 20,
  }),
  menu({
    code: "models.channel-groups",
    parent_code: "group.models",
    type: "menu",
    path: "/models/channel-groups",
    component: "channel-groups",
    label_key: "shell.nav_channel_groups",
    icon: "layers",
    permission_code: "routing.read",
    sort_order: 30,
  }),
  menu({
    code: "models.proxies",
    parent_code: "group.models",
    type: "menu",
    path: "/models/proxies",
    component: "proxies",
    label_key: "shell.nav_proxies",
    icon: "network",
    permission_code: "proxies.read",
    sort_order: 40,
  }),
  menu({
    code: "group.governance",
    type: "directory",
    path: "/governance",
    component: "Layout",
    label_key: "shell.nav_group_governance",
    icon: "users-round",
    sort_order: 50,
  }),
  menu({
    code: "governance.tenants",
    parent_code: "group.governance",
    type: "menu",
    path: "/governance/tenants",
    component: "tenants",
    label_key: "shell.nav_tenants",
    icon: "building-2",
    permission_code: "platform.tenants.read",
    sort_order: 10,
  }),
  menu({
    code: "governance.users",
    parent_code: "group.governance",
    type: "menu",
    path: "/governance/users",
    component: "users",
    label_key: "shell.nav_users",
    icon: "user-round",
    permission_code: "tenant.users.read",
    sort_order: 20,
  }),
  menu({
    code: "governance.roles",
    parent_code: "group.governance",
    type: "menu",
    path: "/governance/roles",
    component: "roles",
    label_key: "shell.nav_roles",
    icon: "shield-check",
    permission_code: "tenant.roles.read",
    sort_order: 30,
  }),
  menu({
    code: "governance.audit",
    parent_code: "group.governance",
    type: "menu",
    path: "/governance/audit-logs",
    component: "audit-logs",
    label_key: "shell.nav_audit_logs",
    icon: "file-text",
    permission_code: "tenant.audit.read",
    sort_order: 40,
  }),
  menu({
    code: "group.system",
    type: "directory",
    path: "/system",
    component: "Layout",
    label_key: "shell.nav_group_system",
    icon: "settings",
    sort_order: 60,
  }),
  menu({
    code: "system.config",
    parent_code: "group.system",
    type: "menu",
    path: "/system/config",
    component: "config",
    label_key: "shell.nav_config",
    icon: "settings",
    permission_code: "system.config.read",
    sort_order: 10,
  }),
  menu({
    code: "system.menus",
    parent_code: "group.system",
    type: "menu",
    path: "/system/menu-management",
    component: "menu-management",
    label_key: "shell.nav_menu_management",
    icon: "menu",
    permission_code: "platform.menus.read",
    sort_order: 20,
  }),
];

export const legacyServicePrincipal = (): ManagementPrincipal => ({
  kind: "service_credential",
  user: {
    id: "service",
    tenant_id: "system",
    username: "admin",
    display_name: "Administrator",
    status: "active",
    must_change_password: false,
    last_login_at: null,
    role_ids: [],
    role_codes: [],
    version: 1,
    created_at: "",
    updated_at: "",
  },
  home_tenant: {
    id: "system",
    slug: "system",
    name: "System Administration",
    type: "system",
    status: "active",
    effective_status: "active",
    expires_at: null,
    description: "",
    version: 1,
    created_at: "",
    updated_at: "",
  },
  effective_tenant: {
    id: "system",
    slug: "system",
    name: "System Administration",
    type: "system",
    status: "active",
    effective_status: "active",
    expires_at: null,
    description: "",
    version: 1,
    created_at: "",
    updated_at: "",
  },
  roles: [],
  menus: LEGACY_SERVICE_MENUS,
  permissions: ["*"],
  platform_admin: true,
});
